Sys.setenv(TAR = "/bin/tar")
options(repos = "https://cloud.r-project.org/")
install.packages("BiocManager")
BiocManager::install(version='3.16', ask = FALSE)
BiocManager::install("MungeSumstats")
BiocManager::install("BSgenome")
BiocManager::install("BSgenome.Hsapiens.1000genomes.hs37d5")
BiocManager::install("BSgenome.Hsapiens.NCBI.GRCh38")
BiocManager::install("GenomicFiles")
